### ISSUE TITLE
Blank space on google colab

### ISSUE THREAD

**Issue by lautman** [LSYS/forestplot#110]
LOVE it, thank you!
For some reason when plotted, it adds blank space in the middle. Even with the toy example, loading your dataset it gives the same plotting.

<img width="1076" alt="image" src="https://github.com/LSYS/forestplot/assets/44987598/20234875-7244-4b71-badd-8a71557577be">

**Comment by LSYS** [comment]
@lautman sorry about that. the package was not developed/tested with colab, which might have a different backend support (e.g., https://github.com/googlecolab/colabtools/issues/616#issuecomment-506829877). unfortunately, you may need to use this package outside colab. I'll flag this as a known issue and hopefully someone familiar with matplotlib underworkings has a solution.
