### ISSUE TITLE
Groupvar results in formatting columns as floats

### ISSUE THREAD

**Issue by jessicahislop** [LSYS/forestplot#111]
I've noticed a 'feature' such that when you do not use 'groupvar', columns of integers are displayed correctly. But once using the 'groupvar' function, it's now formatting the integers as floats. I've searched through the source code but cannot find where/why this is happening. Can anyone who knows the code well point me to where to fix this? Thanks so much!

**Comment by LSYS** [comment]
@jessicahislop do you have an example dataset to reproduce the error?

**Comment by crg-n** [comment]
I have come across the same issue. I can't share my dataset but essentially it occurs with any dataset when including a column of integer values in the dataframe and then displaying that column in the output using annote. It correctly displays as integers without 'groupvar' but enabling 'groupvar' causes the integers to be displayed as floats.
