### ISSUE TITLE
Alignment, Format, and Color issues

### ISSUE THREAD

**Issue by i-akshat-jain** [LSYS/forestplot#112]
Hey, first of thank you for the repo. It helped me a lot with my ongoing project. I was facing some issues with the flexibility of the plots. Places when I have to use a different colour for different y-axis values or if I have to change the font style of the whole plot it is not available. Even though I had to capitalise the Y-axis names I was not able to as it is not available in the description. Could anyone help me out with how to make these work or is it not available in the current version? If not I would love to contribute to this. @juancq @shapiromatron @LSYS.

**Comment by LSYS** [comment]
happy to have you contribute @i-akshat-jain if you have something in mind without breaking what already works. happy to describe more
