### ISSUE TITLE
Coloring Alternate Rows text

### ISSUE THREAD

**Issue by patskowron** [LSYS/forestplot#26]
Hello, I'm really enjoying this package but have one issue. The 'color_alt_rows' setting colors only the plot but doesn't include the text which still makes it difficult to match up and read easily. Would it possible to shade in the text as well? Thanks!

**Comment by LSYS** [comment]
@patskowron thanks so much for using this package.
Do you happen to have an example image of what you want?

This is probably not exactly what you are asking for, but you can highlight the `ylabels` individually by color.

This is what you would have done:
```python
import forestplot as fp
df = fp.load_data("sleep")  # companion example data

ax = fp.forestplot(df,  # the dataframe with results data
              estimate="r",  # col containing estimated effect size 
              ll="ll", hl="hl",  # columns containing conf. int. lower and higher limits
              varlabel="label",  # column containing variable label
              color_alt_rows=True,  # Gray alternate rows
              )

hightlight_color = "gray"
ax.get_yticklabels()[1].set_color(hightlight_color)
```

If you know you want to highlight multiple rows
```python
hightlight_color = "gray"
highlight_rows = [1,3,5,7,9,11,13]
for row in highlight_rows:
    ax.get_yticklabels()[row].set_color(hightlight_color)
```

**Comment by LSYS** [comment]
@patskowron Shading in the area around the text is trickier. The current `matplotlib` backend I use at the moment does not seem to support this.

If you know how to do it and want to make a PR, I'm happy to discuss more here.
