### ISSUE TITLE
Maintain label character formatting (making no string normalisation the default)

### ISSUE THREAD

**Issue by srison-qmul** [LSYS/forestplot#27]
![thumbnail_image](https://user-images.githubusercontent.com/85877085/196449114-02f3e867-7740-4cf1-97bf-6f5733930f79.png)
Label "IMD quintile" is represented as "Imd quintile"
I would propose that the default setting would be to maintain label strings as stated (with perhaps the option to switch on a "string normalisation" option.

**Comment by LSYS** [comment]
Thanks @srison-qmul  for opening the issue. 

Will work on this. 

In the next release, `forestplot` will preserve string capitalisation until users explicitly call an option for string normalisation.

**Comment by LSYS** [comment]
closed in [v0.2.0](https://github.com/LSYS/forestplot/releases/tag/v0.2.0).
