### ISSUE TITLE
Excess Whitespace Error in Jupyter

### ISSUE THREAD

**Issue by sjiang40** [LSYS/forestplot#37]
I followed the install and quick start instructions in the README, but I'm having an issue with excess whitespace being added between the variable labels and the plot. Below are screenshots of the example as well as example with customization 5. The whitespace is added regardless of the width of the overall forest plot.

I am using Jupyter version 6.5.2 and Python 3.9.15 via Anaconda.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/119698143/205362722-9c5257f0-26b6-4aa3-a62b-1ac7a9decb3f.png">
<img width="972" alt="image" src="https://user-images.githubusercontent.com/119698143/205362777-4f5adcab-2b6f-4277-809e-4b97e77e44b9.png">

**Comment by sjiang40** [comment]
1. I ran `pip install --upgrade forestplot` and confirmed that it's on v0.2.0
2. My `matplotlib` version is 3.5.3

Rerunning the code with these 2 confirmed versions, I still get the same error

**Comment by sjiang40** [comment]
@LSYS I managed to piece together a temporary fix for my issue by manually moving the y tick labels and table lines. Here's the code for my temporary fix; perhaps that can help with finding the issue.

```
ax = fp.forestplot(
    df,  # the dataframe with results data
    estimate="r",  # col containing estimated effect size 
    ll="ll", hl="hl",  # lower & higher limits of conf. int.
    varlabel="label",  # column containing the varlabels to be printed on far left
    capitalize="capitalize",  # Capitalize labels
    pval="p-val",  # column containing p-values to be formatted
    annote=["n", "power", "est_ci"],  # columns to report on left of plot
    annoteheaders=["N", "Power", "Est. (95% Conf. Int.)"],  # ^corresponding headers
    rightannote=["formatted_pval", "group"],  # columns to report on right of plot 
    right_annoteheaders=["P-value", "Variable group"],  # ^corresponding headers
    groupvar="group",  # column containing group labels
    group_order=["labor factors", "occupation", "age", "health factors", 
               "family factors", "area of residence", "other factors"],                   
    xlabel="Pearson correlation coefficient",  # x-label title
    xticks=[-.4,-.2,0, .2],  # x-ticks to be printed
    sort=True,  # sort estimates in ascending order
    table=True,  # Format as a table
    # Additional kwargs for customizations
    **{
         "marker": "D",  # set maker symbol as diamond
         "markersize": 30,  # adjust marker size
         "xlinestyle": (0, (10, 5)),  # long dash for x-reference line 
         "xlinecolor": "#808080",  # gray color for x-reference line
         "xtick_size": 12,  # adjust x-ticker fontsize
    }  
)

ax.tick_params(axis='y', pad=490)

lines = ax.get_lines()
for line in lines[1:3]:
    line.set_xdata([-1.73, -.43])

plt.show()
```

The above code generates the following image

![image](https://user-images.githubusercontent.com/119698143/206818842-34be4d4f-c0e0-4106-8c5a-fd829386e181.png)

**Comment by LSYS** [comment]
@sjiang40 One possible (short-term) solution is to freeze `matplotlib` to an older version. E.g.,

```console
pip install matplotlib==3.4.3
```
and see if that works (best to do it in an env). Let me know if it works for you.

Regarding your follow-up message, it's not ideal to hardcode the limits but they may point to a more general solution (thanks for this!). 
I should be able to find time to work on this properly around the end of the year.

**Comment by LSYS** [comment]
@sjiang40 After more investigation, the problem is likely with `matplotlib-inline`. 

I can reproduce the wrong figures with `matplotlib-inline>=0.1.4` but not with `matplotlib-inline<=0.1.3`.

Can you confirm that you are using `matplotlib-inline>=0.1.4`?
```python
import matplotlib_inline
matplotlib_inline.__version__
```

If so, the solution is likely to freeze `matplotlib-inline` to `0.1.3` and below:

```bash
pip install "matplotlib-inline<=0.1.3"
```
