### ISSUE TITLE
change font to support Chinese

### ISSUE THREAD

**Issue by Hansyvea** [LSYS/forestplot#60]
currently, Chinese Character will not show in the plot and it is the same for korean, japanese and so on. How to change font setting to let it support Chinese? thx in advance

**Comment by LSYS** [comment]
Hi @Hansyvea thank you for raising this issue.

CJK characters (Chinese, Japanese, Korean) are not supported by default in `matplotlib`. So more investigation and work will be needed to support cjk within `forestplot`.

Implementing CJK is not a priority for now (just a heads up). So you may need to tweak font properties directly from `matplotlib` to get what you need.

This resource might be useful: [Displaying CJK Characters in Matplotlib Plots](https://albertauyeung.github.io/2020/03/15/matplotlib-cjk-fonts.html/) (but I have yet to try it out myself).

**Comment by highwindmx** [comment]
matplotlib.rcParams['font.monospace'] = ['SimHei'] can help you
