### ISSUE TITLE
Adding lines in X axis

### ISSUE THREAD

**Issue by ksarathbabu** [LSYS/forestplot#63]
Is there a way to move the xaxis line from 0 to 1 or add a new line in Xaxis?

**Comment by LSYS** [comment]
@ksarathbabu, use the `xline` option to place the x-axis line where you want:

```python
import forestplot as fp

df = fp.load_data("sleep")

ax = fp.forestplot(df,  # the dataframe with results data
              estimate="r",  # col containing estimated effect size 
              ll="ll", hl="hl",  # columns containing conf. int. lower and higher limits
              varlabel="label",  # column containing variable label
              xline=.15,  # <---- Add this line here
              )
```
![image](https://user-images.githubusercontent.com/10510571/226511276-b0eae2ac-aed5-4bba-85d3-2273bef88445.png)

If you want to add even more lines, check out the [axvline](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.axvline.html) from `matplotlib`. You can assign the axes object from `fp.forestplot` (like above) and then do a `ax.axvline(-.15)`. See the link to the `axvline` docs for more parameters to tweak.

**Comment by LSYS** [comment]
can you show an example of what you mean?

**Comment by buhtz** [comment]
The `xline` argument seems not to be part of the documentation. I am right, or did I miss something?

**Comment by LSYS** [comment]
yes, thanks for pointing that out, this should in the next release
