### ISSUE TITLE
Pass axis to forestplot call

### ISSUE THREAD

**Issue by juancq** [LSYS/forestplot#65]
Is there any way to pass an existing axis to forestplot? This would enable subplots.

**Comment by LSYS** [comment]
hi @juancq unfortunately, the current API does not allow an existing axis to be passed in. The first time an axis is created is in [`_make_forestplot(...)`](https://github.com/LSYS/forestplot/blob/30f1eef6ae64fc9145af2b4ab94f4fd25a71375b/forestplot/plot.py#L330)

https://github.com/LSYS/forestplot/blob/30f1eef6ae64fc9145af2b4ab94f4fd25a71375b/forestplot/plot.py#L360

which takes arguments from the user-facing [`forestplot(...)`](https://github.com/LSYS/forestplot/blob/30f1eef6ae64fc9145af2b4ab94f4fd25a71375b/forestplot/plot.py#L50).

Can you say a bit more about what plot you have in mind?

**Comment by juancq** [comment]
This is what I have done: 
https://github.com/LSYS/forestplot/compare/main...juancq:forestplot:main

I am making a plot with multiple forest plots side by side (as in a grid).

**Comment by LSYS** [comment]
Great, would you like to make a pull request @juancq?

**Comment by LSYS** [comment]
Merged in #98.
