### ISSUE TITLE
Change group variable font size

### ISSUE THREAD

**Issue by amaa11** [LSYS/forestplot#71]
Dear all,

Thanks so much for such amazing tool.
My question is how can I change the font size for groupvar ?  
When I change the fontsize value, nothing happen for groupvar in term of font size.
Any suggestion please?

best

**Comment by LSYS** [comment]
hi @amaa11, use the (as of now) undocumented `kwarg` `grouplab_size`.

```python
import forestplot as fp

df = fp.load_data("sleep")

fp.forestplot(df,  # the dataframe with results data
              estimate="r",  # col containing estimated effect size 
              varlabel="label",  # column containing variable label
              groupvar="group",  # Add variable groupings 
              )
```
![image](https://user-images.githubusercontent.com/10510571/235338039-b29bb2be-9866-4fd1-b5dc-5a86d973dadc.png)

Makeing the groupvar font large using `grouplab_size=15`:

```python
fp.forestplot(df,  # the dataframe with results data
              estimate="r",  # col containing estimated effect size 
              varlabel="label",  # column containing variable label
              groupvar="group",  # Add variable groupings 
              grouplab_size=18,
              )
```
![image](https://user-images.githubusercontent.com/10510571/235338302-f6e4cef7-ec8b-4b16-badc-63b2d6ebc6d1.png)
