### ISSUE TITLE
Save SVG version of the forest plot

### ISSUE THREAD

**Issue by Mihiretukebede** [LSYS/forestplot#72]
Thanks for this great library! I prefer to write my plots in SVG since it has a much better resolution than PNG or JPEG formats. I tried to use `plt.savefig()` function but it writes an empty file. Is it not possible to save the plot outputs in svg? It would be great if this feature is added.

**Comment by LSYS** [comment]
hi @Mihiretukebede, thanks for giving this package a go. Do you have a reproducible example? I seem to have no issues saving in SVG.

Perhaps see also issue #38. Specifically https://github.com/LSYS/forestplot/issues/38#issuecomment-1366706791

**Comment by Mihiretukebede** [comment]
I tried saving using the following but it didn't work. 
`plt.savefig("plot.svg")`

**Comment by LSYS** [comment]
@Mihiretukebede try this
```python
plt.savefig("plot.svg", bbox_inches="tight")
```

**Comment by Mihiretukebede** [comment]
`plt.savefig("Python_Forest_plot.svg", bbox_inches="tight")
`
Unfortunately, this results in an error. 
**_AttributeError: 'AxesSubplot' object has no attribute 'savefig'_**

**Comment by LSYS** [comment]
@Mihiretukebede can you provide more context?
