### ISSUE TITLE
Setting 95% confidence interval limits 

### ISSUE THREAD

**Issue by Mihiretukebede** [LSYS/forestplot#75]
I have data of about 20 rows. The confidence intervals are between 0 and 5 except for two rows with confidence interval labels ranging between 1.5 and 40. Plotting them all together makes the intervals very narrow because they are compressed by the wide intervals of the two records. I wanted to add a confidence interval limit to make the plot readable. I used `xticks=[0,1,5, 10]` and `set_xlim(0, 10)`. But this makes my plot bad. 
This was the graph without adding `set_xlim(0,10)`

![image](https://github.com/LSYS/forestplot/assets/44161975/e0b71bc4-6e29-4b29-97c8-30842fb0431a)
After 
![image](https://github.com/LSYS/forestplot/assets/44161975/0743f212-30d9-4a2f-ba31-289e879c28f0)

**Comment by LSYS** [comment]
hi @Mihiretukebede, can you give a (reproducible) example?
