### ISSUE TITLE
BUG failing when running on matplotlib 3.8

### ISSUE THREAD

**Issue by maikia** [LSYS/forestplot#82]
Thanks for your great work,

I tried running your code with the newest version of matplotlib (3.8) but unfortunately it fails.

Error from matplotlib: 

```*** AttributeError: 'YTick' object has no attribute 'label'```

originating at `forsetplot/graph_utils.py` line: ```pad = max(
        T.label.get_window_extent(renderer=fig.canvas.get_renderer()).width
        for T in yax.majorTicks
    )```

Downgrading to matplotlib 3.7.3 solves the issue

**Comment by Tian-hao** [comment]
Matplotlib 3.8.0 updated the Tick object. 

Changing `T.label` to `T.label1` should solve the problem.
